### ISSUE TITLE
Can't find the Release folder

### ISSUE THREAD

**Issue by xiaoyongcheng** [streamlabs/obs-studio-node#372]
My order:
git submodule update --init --recursive
mkdir build
cd build
cmake .. -G"Visual Studio 15 2017" -A x64
cmake -DCMAKE_BUILD_TYPE=Release .
cmake --build .
cpack -G ZIP

cmake --build . prompts no nan.h, I tried to put nan.h in the client folder and no error.
cpack prompts no release folder，I add the order CMAKE_BUILD_TYPE, but Release never seen.
Please tell me what did I do wrong.very greatful!

**Comment by RodrigoHolztrattner** [comment]
I believe you are missing the `yarn install` command before doing these other commands.
This instruction was missing from our readme file, thanks for pointing, it will be updated soon.

**Comment by xiaoyongcheng** [comment]
first appreciate your reply, sorry I didn't see it in time. I am a fresh, sorry to bother you.

- [X] `yarn install` is helpful, it's solve something dep.

- [ ] but in the commend `cmake .. -G"Visual Studio 15 2017" -A x64` I always seen some messy code(some Chinese messy word) in my terminal (At other times the display is normal), I can't know what the error is. Executing the command again later is successful. but `cmake build .` can't create Release folder, only Debug in client,server and _dep/stackwalker-build.This affect `cpack` find folder.

Which configuration did I have a problem with. It's the issue of Release?or use.Thanks a lot.



---------------------------------------------------------------------------------------------------
**Please ignore the following, I just want to update electron and node to extend the application.**

I tryed copy all of file in Debug to Release, it seem worked. but when i use it ,terminal reported 'obs_studio_client.node' was compiled against a different Node.js version using. Same as the one reported by the package you provided [directly]("https://obsstudionodes3.streamlabs.com/obs-studio-node-v0.4.22-iojs-v2.0.8.tar.gz"). this package also report same problem, so that I chose to compile the project myself. I use the same node version12.0.0 , the part electron ver 5.0.0.The NODE_MODULE_VERSION must be 70, but why compiled version is 69.
[https://nodejs.org/zh-cn/download/releases/#ref-1](url)

Here is the whole report:
Error: The module '\\?\C:\Users\73665\Desktop\mxc-obs\node_modules\obs-studio-node\obs_studio_client.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\73665\Desktop\mxc-obs\node_modules\obs-studio-node\module.js:3:13)
    at Object.<anonymous> (C:\Users\73665\Desktop\mxc-obs\node_modules\obs-studio-node\module.js:95:3)

**Comment by EddyGharbi** [comment]
Let me know if this is still an issue, also make sure to correctly set `CMAKE_INSTALL_PREFIX` when configuring cmake.

**Comment by liuyaxin** [comment]
here is a command for Release

cmake --build . --config Release
